#!/usr/bin/env bash

if [ -z "$MMDAPP" ]; then
	set -e
	export MMDAPP="$( cd $(dirname "$0")/../../../.. ; pwd )"
	echo "$0: Working in: $MMDAPP"  >&2
	[ -d "$MMDAPP/source" ] || ( echo "⛔ ERROR: expecting 'source' directory." >&2 && exit 1 )
fi

if [ -z "$MDLT_ORIGIN" ] || ! type DistroSystemContext >/dev/null 2>&1 ; then
	. "${MDLT_ORIGIN:=$MMDAPP/.local}/myx/myx.distro-system/sh-lib/SystemContext.include"
	DistroSystemContext --distro-path-auto
fi

RebuildActions(){
	if [ -z "$MDSC_SOURCE" ]; then
		echo "⛔ ERROR: DistroContext is not set!" >&2
		set +e ; return 1
	fi

	local TMP_DIR="$( mktemp -d -t "rebuild-actions-XXXXXXXX" )"
	if [ $? -ne 0 ]; then
		echo "⛔ ERROR: Can't make temporary actions directory $TMP_DIR, exiting..." >&2
		set +e ; return 1
	fi
	echo "RebuildActions: Using temporary actions directory: $TMP_DIR"


	if [ "$1" == "--test1" ]; then
		cd "$MDSC_SOURCE"
		find $( DistroSystemContext --index-projects cat | tr '\n' ' ' ) -type d -name "actions" -prune
		exit 0
	fi
	if [ "$1" == "--test2" ]; then
		cd "$MDSC_SOURCE"
		find . -type d -name "actions" -exec sh -c 'test -f "$0/../project.inf" && echo "$0"' {} \; -prune
		exit 0
	fi
	if [ "$1" == "--test3" ]; then
		Distro ListDistroProjects --select-projects-with-path "-d" "actions"
		exit 0
	fi
	
	set -e
	local projectName actionFullName actionLocation actionSourceFile

	Distro AllActions --full \
	| while read -r projectName actionFullName; do

		actionLocation="$TMP_DIR/${actionFullName#$projectName/actions/}"
		
		if [ -f "$MDSC_SOURCE/$actionFullName" ]; then
			if [ "$MDSC_SOURCE" != "$MMDAPP/source" ] && [ -f "$MMDAPP/source/$actionFullName" ]; then
				actionSourceFile="$MMDAPP/source/$actionFullName"
			else
				actionSourceFile="$MDSC_SOURCE/$actionFullName"
			fi
		elif [ -f "$MDLT_ORIGIN/$actionFullName" ]; then
			actionSourceFile="$MDLT_ORIGIN/$actionFullName"
		else
			actionSourceFile="$MMDAPP/source/$actionFullName"
		fi
		
		printf "Processing: %s \n \t \t ^ %s\n" "${actionLocation#$TMP_DIR/}" "${actionFullName}" >&2

		mkdir -p "$( dirname "$actionLocation" )"

		case "$actionFullName" in
			*.sh)
				## source code of script being created:
				{
					echo '#!/usr/bin/env bash'
					echo '## this file is generated by [Source RebuildActions] utility'
					
					echo 'ActionExecutionWrap(){'

					echo 	"local actionScript='${actionFullName#"$projectName/actions/"}'"
					echo 	"local actionFullName='$actionFullName'"
					
					echo 	"set -e"

					echo 	'local actionPath="$( realpath "$0" )"'

					echo 	'[ full != "$MDSC_DETAIL" ] || set -x'
					
					echo 	'if [ -n "${MMDAPP-}" ]; then'

					echo 		'[ -z "$MDSC_DETAIL" ] || echo "> Action $actionFullName: using context settings: $MMDAPP" >&2'

					echo 	'elif [ "$actionPath" != "${actionPath%"/source/$actionFullName"}" ]; then'

					echo 		'export MMDAPP="${actionPath%"/source/$actionFullName"}"'
					echo 		'[ -z "$MDSC_DETAIL" ] || echo "> Action $actionFullName: calculated settings from source: $MMDAPP" >&2'

					echo 	'elif [ "$actionPath" != "${actionPath%"/actions/$actionScript"}" ]; then'

					echo 		'export MMDAPP="${actionPath%"/actions/$actionScript"}"'
					echo 		'[ -z "$MDSC_DETAIL" ] || echo "> Action $actionFullName: calculated settings from action: $MMDAPP" >&2'

					echo 	'else'

					echo 		'echo "! Action $actionFullName: ⛔ ERROR: cant calculate distro root directory!" >&2'
					echo		'set +e ; return 1'

					echo 	'fi'
					
					echo 	'[ -d "$MMDAPP/source" ] || {'
					echo 		'echo "! Action $actionFullName: ⛔ ERROR: source directory does not exist!" >&2'
					echo		'set +e ; return 1'
					echo 	'}'
					
					echo 	'if [ -z "$MDLT_ORIGIN" ] || ! type DistroSystemContext >/dev/null 2>&1; then'
					echo 		'. "${MDLT_ORIGIN:-$MMDAPP/.local}/myx/myx.distro-system/sh-lib/SystemContext.include"'
					echo 		'DistroSystemContext --distro-path-auto'
					echo 	'fi'

					echo 	'if [ -f "$MMDAPP/source/$actionFullName" ]; then'
					echo 		'. "$MMDAPP/source/$actionFullName"' 
					echo 	'elif [ -f "${MDLT_SOURCE:-$MMDAPP/source}/$actionFullName" ]; then'
					echo 		'. "${MDLT_SOURCE:-$MMDAPP/source}/$actionFullName"' 
					echo 	'elif [ -f "${MDLT_ORIGIN:-$MMDAPP/.local}/$actionFullName" ]; then'
					echo 		'. "${MDLT_ORIGIN:-$MMDAPP/.local}/$actionFullName"' 
					echo 	'else'
					echo 		'echo "! Action $actionFullName: ⛔ ERROR: cant locate action executable!" >&2'
					echo		'set +e ; return 1'
					echo 	'fi'

					echo '}'
					
					echo 'ActionExecutionWrap "$@"'
				} > "$actionLocation"
				chmod ug=rwx,o=r "$actionLocation" &
				continue
			;;
			*.url)
				if grep -q '\[InternetShortcut\]' "$actionSourceFile" || [ "$( wc -l < "$actionSourceFile" )" -gt 1 ]; then
					## sym-link is being created:
					ln -fs "$actionSourceFile" "$actionLocation"
					chmod -h ug=rwx,o=r "$actionLocation"  &
					continue
				fi
				local SRCCODE="`cat "$actionSourceFile"`"
				local WRKPATH
				if [ "$MDSC_SOURCE" != "$MMDAPP/source" ] && [ -f "$MMDAPP/source/$projectName/$SRCCODE" ]; then
					local SRCCODE="file://$MMDAPP/source/$projectName/$SRCCODE"
					local WRKPATH="$MMDAPP/source/$projectName"
				else
					local SRCCODE="file://$MDSC_SOURCE/$projectName/$SRCCODE"
					local WRKPATH="$MDSC_SOURCE/$projectName"
				fi

				## source code of script being created:
				{
					echo "[InternetShortcut]"
					echo "URL=$SRCCODE"
					echo "WorkingDirectory=$WRKPATH" 
				} > "$actionLocation"
				chmod ug=rwx,o=r "$actionLocation" &
				continue
			;;
			*)
				## sym-link is being created:
				ln -fsv "$actionSourceFile" "$actionLocation"
				chmod -h ug=rwx,o=r "$actionLocation" &
				continue
			;;
		esac
	done
	
	wait
	
	rsync -irltoODC $( [ "--no-delete" = "$1" ] || echo "--delete" ) \
		--chmod=ug+rwx \
		"$TMP_DIR/" \
		"$MMDAPP/actions" \
	2>&1 \
	| (grep --line-buffered -e '^>f' -e '^cd' -e '^\*' || :) \
	| (grep -v --line-buffered -E '>f\.\.t\.+ ' || :) \
	>&2 # output to stderr

	rm -rf "$TMP_DIR"
}

case "$0" in
	*/sh-scripts/RebuildActions.fn.sh) 
		RebuildActions "$@"
	;;
esac
